export interface CourseLink {
  title: string
  instructor: string
  url: string
  specific?: boolean
}

const FC = 'https://fungclass.fhl.net/'

export const BOOK_COURSES: Record<string, CourseLink[]> = {
  '創世記':         [{ title: '摩西五經', instructor: '賴建國', url: FC + 'Moses/' }, { title: '創世記逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Gen/s.html', specific: true }],
  '出埃及記':       [{ title: '摩西五經', instructor: '賴建國', url: FC + 'Moses/' }, { title: '出埃及記逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Exodus/s.html', specific: true }],
  '利未記':         [{ title: '摩西五經', instructor: '賴建國', url: FC + 'Moses/' }, { title: '利未記逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'LEVI/s.html', specific: true }],
  '民數記':         [{ title: '摩西五經', instructor: '賴建國', url: FC + 'Moses/' }, { title: '民數記逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Numbers/s.html', specific: true }],
  '申命記':         [{ title: '摩西五經', instructor: '賴建國', url: FC + 'Moses/' }, { title: '申命記逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Deu/s.html', specific: true }],
  '約書亞記':       [{ title: '舊約歷史書', instructor: '吳獻章', url: FC + 'His/' }],
  '士師記':         [{ title: '舊約歷史書', instructor: '吳獻章', url: FC + 'His/' }, { title: '士師記逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Judges/s.html', specific: true }],
  '路得記':         [{ title: '舊約歷史書', instructor: '吳獻章', url: FC + 'His/' }],
  '撒母耳記上':     [{ title: '舊約歷史書', instructor: '吳獻章', url: FC + 'His/' }],
  '撒母耳記下':     [{ title: '舊約歷史書', instructor: '吳獻章', url: FC + 'His/' }],
  '列王紀上':       [{ title: '舊約歷史書', instructor: '吳獻章', url: FC + 'His/' }],
  '列王紀下':       [{ title: '舊約歷史書', instructor: '吳獻章', url: FC + 'His/' }],
  '歷代志上':       [{ title: '舊約歷史書', instructor: '吳獻章', url: FC + 'His/' }],
  '歷代志下':       [{ title: '舊約歷史書', instructor: '吳獻章', url: FC + 'His/' }],
  '以斯拉記':       [{ title: '舊約歷史書', instructor: '吳獻章', url: FC + 'His/' }],
  '尼希米記':       [{ title: '舊約歷史書', instructor: '吳獻章', url: FC + 'His/' }],
  '以斯帖記':       [{ title: '舊約歷史書', instructor: '吳獻章', url: FC + 'His/' }],
  '約伯記':         [{ title: '詩歌智慧書', instructor: '吳獻章', url: FC + 'Wise/' }, { title: '約伯記逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Job/', specific: true }],
  '詩篇':           [{ title: '詩歌智慧書', instructor: '吳獻章', url: FC + 'Wise/' }, { title: '詩篇逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Psalms/', specific: true }],
  '箴言':           [{ title: '詩歌智慧書', instructor: '吳獻章', url: FC + 'Wise/' }, { title: '箴言逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Prov/', specific: true }],
  '傳道書':         [{ title: '詩歌智慧書', instructor: '吳獻章', url: FC + 'Wise/' }],
  '雅歌':           [{ title: '詩歌智慧書', instructor: '吳獻章', url: FC + 'Wise/' }],
  '以賽亞書':       [{ title: '大先知書', instructor: '吳獻章', url: FC + 'Prophet/' }],
  '耶利米書':       [{ title: '大先知書', instructor: '吳獻章', url: FC + 'Prophet/' }, { title: '耶利米書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Jere/', specific: true }],
  '耶利米哀歌':     [{ title: '大先知書', instructor: '吳獻章', url: FC + 'Prophet/' }],
  '以西結書':       [{ title: '大先知書', instructor: '吳獻章', url: FC + 'Prophet/' }],
  '但以理書':       [{ title: '大先知書', instructor: '吳獻章', url: FC + 'Prophet/' }],
  '何西阿書':       [{ title: '小先知書', instructor: '諸蔡筱楓', url: FC + 'Minor/' }],
  '約珥書':         [{ title: '小先知書', instructor: '諸蔡筱楓', url: FC + 'Minor/' }],
  '阿摩司書':       [{ title: '小先知書', instructor: '諸蔡筱楓', url: FC + 'Minor/' }],
  '俄巴底亞書':     [{ title: '小先知書', instructor: '諸蔡筱楓', url: FC + 'Minor/' }],
  '約拿書':         [{ title: '小先知書', instructor: '諸蔡筱楓', url: FC + 'Minor/' }],
  '彌迦書':         [{ title: '小先知書', instructor: '諸蔡筱楓', url: FC + 'Minor/' }],
  '那鴻書':         [{ title: '小先知書', instructor: '諸蔡筱楓', url: FC + 'Minor/' }],
  '哈巴谷書':       [{ title: '小先知書', instructor: '諸蔡筱楓', url: FC + 'Minor/' }],
  '西番雅書':       [{ title: '小先知書', instructor: '諸蔡筱楓', url: FC + 'Minor/' }],
  '哈該書':         [{ title: '小先知書', instructor: '諸蔡筱楓', url: FC + 'Minor/' }],
  '撒迦利亞書':     [{ title: '小先知書', instructor: '諸蔡筱楓', url: FC + 'Minor/' }],
  '瑪拉基書':       [{ title: '小先知書', instructor: '諸蔡筱楓', url: FC + 'Minor/' }],
  '馬太福音':       [{ title: '福音書', instructor: '劉幸枝博士', url: FC + 'Gospel/' }, { title: '馬太福音逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Mt/s.html', specific: true }],
  '馬可福音':       [{ title: '福音書', instructor: '劉幸枝博士', url: FC + 'Gospel/' }, { title: '馬可福音逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Mk/s.html', specific: true }],
  '路加福音':       [{ title: '福音書', instructor: '劉幸枝博士', url: FC + 'Gospel/' }, { title: '路加福音逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Luke/', specific: true }],
  '約翰福音':       [{ title: '福音書', instructor: '劉幸枝博士', url: FC + 'Gospel/' }, { title: '約翰福音逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'JOHN/', specific: true }],
  '使徒行傳':       [{ title: '使徒行傳逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Act/', specific: true }],
  '羅馬書':         [{ title: '保羅書信', instructor: '多媒體聖經學苑', url: FC + 'Paul/s.html' }, { title: '羅馬書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Romans/', specific: true }],
  '哥林多前書':     [{ title: '保羅書信', instructor: '多媒體聖經學苑', url: FC + 'Paul/s.html' }, { title: '哥林多前書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Co/', specific: true }],
  '哥林多後書':     [{ title: '保羅書信', instructor: '多媒體聖經學苑', url: FC + 'Paul/s.html' }, { title: '哥林多後書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Co/', specific: true }],
  '加拉太書':       [{ title: '保羅書信', instructor: '多媒體聖經學苑', url: FC + 'Paul/s.html' }, { title: '加拉太書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Gal/', specific: true }],
  '以弗所書':       [{ title: '保羅書信', instructor: '多媒體聖經學苑', url: FC + 'Paul/s.html' }, { title: '以弗所書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Ephe/', specific: true }],
  '腓立比書':       [{ title: '保羅書信', instructor: '多媒體聖經學苑', url: FC + 'Paul/s.html' }, { title: '腓立比書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Phil/', specific: true }],
  '歌羅西書':       [{ title: '保羅書信', instructor: '多媒體聖經學苑', url: FC + 'Paul/s.html' }, { title: '歌羅西書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Col/', specific: true }],
  '帖撒羅尼迦前書': [{ title: '保羅書信', instructor: '多媒體聖經學苑', url: FC + 'Paul/s.html' }, { title: '帖撒羅尼迦書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Thes/', specific: true }],
  '帖撒羅尼迦後書': [{ title: '保羅書信', instructor: '多媒體聖經學苑', url: FC + 'Paul/s.html' }, { title: '帖撒羅尼迦書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Thes/', specific: true }],
  '提摩太前書':     [{ title: '保羅書信', instructor: '多媒體聖經學苑', url: FC + 'Paul/s.html' }, { title: '提摩太書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Tim/', specific: true }],
  '提摩太後書':     [{ title: '保羅書信', instructor: '多媒體聖經學苑', url: FC + 'Paul/s.html' }, { title: '提摩太書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Tim/', specific: true }],
  '提多書':         [{ title: '保羅書信', instructor: '多媒體聖經學苑', url: FC + 'Paul/s.html' }, { title: '提多書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Tit/', specific: true }],
  '腓利門書':       [{ title: '保羅書信', instructor: '多媒體聖經學苑', url: FC + 'Paul/s.html' }],
  '希伯來書':       [{ title: '一般書信', instructor: '王良玉博士', url: FC + 'Letters/' }, { title: '希伯來書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Heb/', specific: true }],
  '雅各書':         [{ title: '一般書信', instructor: '王良玉博士', url: FC + 'Letters/' }, { title: '雅各書逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Jas/', specific: true }],
  '彼得前書':       [{ title: '一般書信', instructor: '王良玉博士', url: FC + 'Letters/' }, { title: '彼得書信逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Peter/', specific: true }],
  '彼得後書':       [{ title: '一般書信', instructor: '王良玉博士', url: FC + 'Letters/' }, { title: '彼得書信逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Peter/', specific: true }],
  '約翰一書':       [{ title: '一般書信', instructor: '王良玉博士', url: FC + 'Letters/' }, { title: '約翰書信逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Jn123/', specific: true }],
  '約翰二書':       [{ title: '一般書信', instructor: '王良玉博士', url: FC + 'Letters/' }, { title: '約翰書信逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Jn123/', specific: true }],
  '約翰三書':       [{ title: '一般書信', instructor: '王良玉博士', url: FC + 'Letters/' }, { title: '約翰書信逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Jn123/', specific: true }],
  '猶大書':         [{ title: '一般書信', instructor: '王良玉博士', url: FC + 'Letters/' }],
  '啟示錄':         [{ title: '啟示錄逐章精讀', instructor: '多媒體聖經學苑', url: FC + 'Revelation/', specific: true }],
}
